// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBZU6vPNb6xmWS4Hmb40AkFJ_dhHcM1K0',
    appId: '1:412459078793:web:0e62409a23e7ce8b24e258',
    messagingSenderId: '412459078793',
    projectId: 'test-auth-bloc',
    authDomain: 'test-auth-bloc.firebaseapp.com',
    storageBucket: 'test-auth-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVRVoW5thy6Vve9dwt3udvQKSwo_MMEso',
    appId: '1:412459078793:android:defa52b27e05cef424e258',
    messagingSenderId: '412459078793',
    projectId: 'test-auth-bloc',
    storageBucket: 'test-auth-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcoEqkF-AzDLZmzG7QBe0X1kCSduQb1RQ',
    appId: '1:412459078793:ios:cd20c96007023d6224e258',
    messagingSenderId: '412459078793',
    projectId: 'test-auth-bloc',
    storageBucket: 'test-auth-bloc.appspot.com',
    iosClientId: '412459078793-jka21kndiukogrfe1vcbh74gns3007hb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbAuthBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcoEqkF-AzDLZmzG7QBe0X1kCSduQb1RQ',
    appId: '1:412459078793:ios:cd20c96007023d6224e258',
    messagingSenderId: '412459078793',
    projectId: 'test-auth-bloc',
    storageBucket: 'test-auth-bloc.appspot.com',
    iosClientId: '412459078793-jka21kndiukogrfe1vcbh74gns3007hb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbAuthBloc',
  );
}
